version: "3.9"

services:

  mongodb:
    image: public.ecr.aws/docker/library/mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

  customer:
    image: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/r2sqs-eb-customer:latest
    container_name: customer
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    environment:
      PORT: 8001
      AWS_REGION: ${AWS_REGION}
      EVENT_BUS_NAME: ${EVENT_BUS_NAME}
      APP_SECRET: ${APP_SECRET}
      CUSTOMER_SERVICE: CUSTOMER_SERVICE
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/customer?authSource=admin
    networks:
      - app-network

  products:
    image: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/r2sqs-eb-products:latest
    container_name: products
    restart: unless-stopped
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
      - redis
    environment:
      PORT: 8002
      AWS_REGION: ${AWS_REGION}
      EVENT_BUS_NAME: ${EVENT_BUS_NAME}
      APP_SECRET: ${APP_SECRET}
      SHOPPING_SERVICE: SHOPPING_SERVICE
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/products?authSource=admin
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}
      REDIS_URL: redis://redis:6379
    networks:
      - app-network

  shopping:
    image: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/r2sqs-eb-shopping:latest
    container_name: shopping
    restart: unless-stopped
    ports:
      - "8003:8003"
    depends_on:
      - mongodb
    environment:
      PORT: 8003
      AWS_REGION: ${AWS_REGION}
      EVENT_BUS_NAME: ${EVENT_BUS_NAME}
      APP_SECRET: ${APP_SECRET}
      SHOPPING_SERVICE: SHOPPING_SERVICE
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/shopping?authSource=admin
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}
    networks:
      - app-network

  gateway:
    image: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/r2sqs-eb-gateway:latest
    container_name: gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - customer
      - products
      - shopping
    environment:
      PORT: 8000
      CUSTOMER_SERVICE_URL: ${CUSTOMER_SERVICE_URL:-http://customer:8001}
      PRODUCT_SERVICE_URL: http://products:8002
      SHOPPING_SERVICE_URL: ${SHOPPING_SERVICE_URL:-http://shopping:8003}
    networks:
      - app-network

volumes:
  mongo_data:


networks:
  app-network:
    driver: bridge
